# Generated by Django 5.2 on 2025-05-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Напишите заголовок', max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Напишите содержимое', verbose_name='Содержимое ')),
                ('image', models.ImageField(blank=True, help_text='Загрузите превью', null=True, upload_to='blog/photo', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.IntegerField(default=0)),
                ('publication_attribute', models.BooleanField(default=True)),
            ],
        ),
    ]
