# Generated by Django 5.2 on 2025-05-06 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напишите категорию', max_length=50, verbose_name='Категория')),
                ('description', models.TextField(help_text='Напишите описание категории', max_length=350, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Напишите название товара', max_length=50, verbose_name='Название товара')),
                ('description', models.TextField(help_text='Напишите описание товара', verbose_name='Описание товара')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение товара', null=True, upload_to='product/photo', verbose_name='Изображение')),
                ('price', models.IntegerField(default=0, help_text='Введите цену продукта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Напишите категорию товара', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['price', 'name', 'category'],
            },
        ),
    ]
